### ISSUE TITLE
Unable to move forward with Vagrant

### ISSUE THREAD

**Issue by OSDaramola** [imnowdevops/ddc-material#5]
Hello Mrv Imran,
I am unable to move forward in my lecture because everytime i typed mkdir /f/vagrant-vms command, This is what vi get 
($ mkdir /f/vagrant-vms mkdir: cannot create directory ‘/f/vagrant-vms’: No such file or directory.
I really need help with ithis i have rebooted it several times

**Comment by devopshydclub** [comment]
That is my folder, I have f drive in my systm, you have mention your own path of the folder.

**Comment by OSDaramola** [comment]
> 
Yes sir i figured it out already i wasn't pay attention before. Thank you
